app:
  bot:
    discordToken:
    discordClientId:
    forceReloadCommands: false
    closedSupportTicketCategory: 'Closed Support Tickets'
    openSupportTicketCategory: 'Support Tickets'
  redis:
    defaultTTL: 604800
    options:
      url: redis://127.0.0.1
  axios:
    baseUrl:
    accessToken:
  messages:
    error500: Internal error. Please contact <@647535196039806979>.
    noSupporterRoleSetup: This server has no supporter role setup. Please contact an administrator.
    errorNotInGuild: This command can only be used in a server.
